Repository anime-team-pet-projects/lavochki-nsk, pull requests merged in 2023-02, with the labels that each got.

#174 feat: FD-20 | Рефактор кода, изменена библиотека яндекс карты
  app/components/Common/ui/Benches/BenchesMap/BenchesMapPlacemarks/index.tsx
  app/components/Common/ui/Benches/BenchesMap/index.tsx
  app/components/pages/BenchDetail/BenchDetailComment/index.tsx
  app/components/pages/BenchDetail/BenchDetailMap/index.tsx
  app/components/pages/Benches/BenchesSort/BenchesSort.constant.ts
  app/components/pages/Benches/BenchesSort/BenchesSort.tsx
  app/components/pages/Home/HomeMap/index.tsx
  package-lock.json
  package.json
  pages/_document.tsx
  pages/benches/BenchesPage.constant.ts
  pages/benches/[id]/BenchDetail.constant.ts
  pages/benches/[id]/index.tsx
  pages/benches/index.tsx
  pages/index.tsx
Labels: frontend, change

#176 change: FD-19 | Изменен зум контроль
  app/components/Common/ui/Benches/BenchesMap/index.tsx
  app/components/pages/Home/HomeMap/HomeMap.style.ts
  app/types/map.type.ts
  pages/benches/[id]/index.tsx
  pages/index.tsx
Labels: frontend, change

#178 change: FD-21 | Изменена кнопка авторизации
  app/components/Layouts/DefaultLayout/DefaultLayoutHeader/DefaultLayoutHeader.type.ts
  app/components/Layouts/DefaultLayout/DefaultLayoutHeader/DefaultLayoutHeaderAuthButton/DefaultLayoutHeaderAuthButton.style.ts
  app/components/Layouts/DefaultLayout/DefaultLayoutHeader/DefaultLayoutHeaderAuthButton/index.tsx
  app/components/Layouts/DefaultLayout/DefaultLayoutHeader/index.tsx
  next.config.js
Labels: frontend, feature

#179 fix: FD-22 | Исправлена ошибка при переходе между страницами. Надо сделать нормально
  app/components/Common/ui/Benches/BenchesMap/BenchesMapPlacemarks/index.tsx
  app/components/Common/ui/Benches/BenchesMap/index.tsx
  app/components/Layouts/DefaultLayout/DefaultLayoutHeader/index.tsx
  app/components/pages/Home/HomeBench/index.tsx
  pages/benches/[id]/BenchDetail.constant.ts
  pages/benches/[id]/index.tsx
Labels: frontend, fix

#183 feat: FD-23 | Добавлена возможность сброса карты к изначальному состояни
  app/assets/icons/reset.svg
  app/components/Common/ui/Benches/BenchesMap/index.tsx
  app/components/pages/Home/HomeMap/HomeMap.style.ts
  app/components/pages/Home/HomeMap/index.tsx
  pages/index.tsx
Labels: frontend, feature

#188 Исправлена ошибка с падением Redis
  docker-compose.yaml
Labels: backend, fix

#189 Добавлен endpoint для получения всех лавочек без ограничений, исправлен комментарий для swagger
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  internal/policy/benches/policy.go
  internal/service/benches/service.go
  internal/transport/httpv1/benches/benches.go
Labels: backend, feature

#190 Добавлен pre-commit
  .pre-commit-config.yaml
Labels: backend, feature

#191 Добавлена возможность удаления комментариев
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  internal/policy/comments/policy.go
  internal/repository/postgres/comments/repository.go
  internal/service/comments/service.go
  internal/transport/httpv1/comments/comments.go
Labels: backend, feature

#192 refactor: FD-24 | Рефактор
  README.md
  app/components/Common/ui/Bench/BenchCard/BenchCardSkeleton/BenchCardSkeleton.tsx
  app/components/Common/ui/Benches/BenchesMap/BenchesMap.tsx
  app/components/Common/ui/Benches/BenchesMap/BenchesMapPlacemarks/BenchesMapPlacemarks.tsx
  app/components/Common/ui/CommonLoader/CommonLoader.tsx
  app/components/Common/ui/CommonSnackbar/CommonSnackbar.tsx
  app/components/Common/ui/ImagePreview/ImagePreview.tsx
  app/components/Layouts/DefaultLayout/DefaultLayoutFooter/DefaultLayoutFooter.tsx
  app/components/Layouts/DefaultLayout/DefaultLayoutHeader/DefaultLayoutHeader.tsx
  app/components/Layouts/DefaultLayout/DefaultLayoutHeader/DefaultLayoutHeaderAuthButton/DefaultLayoutHeaderAuthButton.tsx
  app/components/Layouts/DefaultLayout/DefaultLayoutMenu/DefaultLayoutMenu.tsx
  app/components/pages/BenchDetail/BenchDetailComment/BenchDetailComment.tsx
  app/components/pages/BenchDetail/BenchDetailComment/BenchDetailCommentReport/BenchDetailCommentReport.tsx
  app/components/pages/BenchDetail/BenchDetailComment/BenchDetailCommentSend/BenchDetailCommentSend.tsx
  app/components/pages/BenchDetail/BenchDetailComments/BenchDetailComments.tsx
  app/components/pages/BenchDetail/BenchDetailMap/BenchDetailMap.tsx
  app/components/pages/BenchDetail/BenchDetailNear/BenchDetailNear.tsx
  app/components/pages/BenchDetail/BenchDetailNear/BenchDetailNearSlider/BenchDetailNearSlider.tsx
  app/components/pages/BenchDetail/BenchDetailSlider/BenchDetailSlider.tsx
  app/components/pages/Home/HomeBench/HomeBench.style.ts
  app/components/pages/Home/HomeBench/HomeBench.tsx
  app/components/pages/Home/HomeBench/HomeBenchSlider/HomeBenchSlider.tsx
  app/components/pages/Home/HomeBenches/HomeBenches.tsx
  app/components/pages/Home/HomeMap/HomeMap.tsx
  app/layouts/DefaultLayout/DefaultLayout.tsx
  pages/_app.tsx
  pages/benches/[id]/index.tsx
  pages/benches/index.tsx
  pages/index.tsx
Labels: frontend, refactor

#193 fix: FD-25: Исправлен баг с картой (Но это не точно)
  .babelrc
  app/components/Common/ui/Benches/BenchesMap/BenchesMap.tsx
  app/components/Layouts/DefaultLayout/DefaultLayoutHeader/DefaultLayoutHeader.tsx
  app/components/pages/BenchDetail/BenchDetail.styles.ts
  app/components/pages/Benches/BenchesPage.constant.ts
  app/components/pages/Benches/BenchesPage.style.ts
  app/components/pages/Home/HomeBench/HomeBench.tsx
  pages/benches/[id]/index.tsx
  pages/benches/index.tsx
Labels: invalid, frontend, fix

#194 Обновлены пакет в go.mod
  go.mod
  go.sum
Labels: backend

#196 feat: FD-26 | Добавлен текст с TODO
  pages/benches/[id]/index.tsx
Labels: frontend, feature
