Repository anime-team-pet-projects/lavochki-nsk, pull requests merged in 2023-03, with the labels that each got.

#198 Fix: Исправлена авторизация
  internal/repository/postgres/users/repository.go
  internal/service/users/service.go
Labels: backend, fix

#199 Исправлена ошибка с созданием лавочки из панели администратора
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  internal/dto/benches.go
  internal/policy/benches/policy.go
  internal/transport/httpv1/benches/benches.go
Labels: backend, fix

#200 Добавлены дополнительные поля в список лавочек с пагинацией
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  internal/domain/benches.go
  internal/policy/benches/policy.go
  pkg/telegram/manager.go
Labels: backend, feature

#201 Избавился от DTO в сервисах
  internal/domain/bot.go
  internal/dto/users.go
  internal/policy/bot/policy.go
  internal/service/bot/service.go
  internal/transport/httpv1/bot/bot.go
Labels: backend, refactor

#202 Оптимизировано время сборки docker-контейнера
  Dockerfile
Labels: backend, feature

#205 Добавлено поле "street" у лавочки
  .env.example
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  go.mod
  go.sum
  internal/applications/initiator/app.go
  internal/config/config.go
  internal/domain/benches.go
  internal/policy/benches/policy.go
  internal/repository/postgres/benches/model.go
  internal/repository/postgres/benches/repository.go
  migrations/000002_initial_benches_table.up.sql
  pkg/maps/interfaces.go
  pkg/maps/yandex.go
Labels: backend, feature

#207 fix / feat: DD-11 | Реализовано добавление лавочки, исправлена ошибка отображения данных
  src/assets/icons/no-data.svg
  src/components/Common/CommonNoData/CommonNoData.tsx
  src/components/layouts/DefaultLayout/DefaultLayoutRoutes/DefaultLayoutRoutes.constant.tsx
  src/components/pages/Benches/BenchesDetail/index.tsx
  src/components/pages/Benches/BenchesDialog/BenchesDialogCreate/index.tsx
  src/components/pages/Benches/BenchesDialog/BenchesDialogImages/index.tsx
  src/components/pages/Benches/BenchesDialog/BenchesDialogUpdate/index.tsx
  src/components/pages/Benches/BenchesTable/index.tsx
  src/layouts/DefaultLayout/index.tsx
  src/main.tsx
  src/pages/Benches/index.tsx
  src/pages/BenchesModeration/index.tsx
  src/pages/Comments/CommentsPage.tsx
  src/pages/Home/index.tsx
  src/pages/ReportComments/index.tsx
  src/pages/Tags/index.tsx
  src/pages/Users/index.tsx
  src/services/Bench/BenchService.ts
  src/styles/general.scss
  src/styles/index.scss
  src/styles/resources/mixins/_color.scss
  src/styles/resources/mixins/_fonts.scss
  src/styles/resources/mixins/_grid.scss
  src/styles/resources/mixins/index.scss
  src/styles/resources/variables/_colors.scss
  src/styles/resources/variables/_fonts.scss
  src/styles/resources/variables/_grid.scss
  src/styles/resources/variables/_sizes.scss
  src/styles/resources/variables/index.scss
  src/types/bench.type.ts
  vite.config.ts
Labels: feature, fix, dashboard

#208 feat: FD-27 | Добавлен функционал "смотреть на карте"
  app/components/Common/ui/CommonLoader/CommonLoader.style.ts
  app/components/Common/ui/CommonLoader/CommonLoader.tsx
  app/components/Common/ui/ImagePreview/ImagePreview.tsx
  app/components/Layouts/DefaultLayout/DefaultLayoutHeader/DefaultLayoutHeader.tsx
  app/components/Layouts/DefaultLayout/DefaultLayoutMenu/DefaultLayoutMenu.tsx
  app/components/pages/BenchDetail/BenchDetailMap/BenchDetailMap.tsx
  app/contexts/mapContext.ts
  app/layouts/DefaultLayout/DefaultLayout.tsx
  app/services/User/UserService.ts
  app/types/map.type.ts
  pages/_app.tsx
  pages/benches/[id]/index.tsx
  pages/benches/index.tsx
  pages/index.tsx
Labels: frontend, feature

#209 fix: FD-28: change add bench
  src/components/pages/Benches/BenchesDialog/BenchesDialogCreate/index.tsx
  src/pages/Benches/index.tsx
  src/types/bench.type.ts
Labels: fix, dashboard

#210 feat: DD-13: Добавлена 404 страница
  src/assets/icons/404.svg
  src/components/layouts/DefaultLayout/DefaultLayoutRoutes/DefaultLayoutRoutes.constant.tsx
  src/components/layouts/DefaultLayout/DefaultLayoutSidebar/DefaultLayoutSidebar.contstant.ts
  src/pages/NotFound/NotFoundPage.tsx
  src/pages/Tags/index.tsx
Labels: feature, dashboard

#211 Исправлен баг с созданием лавочки с улицей, добавлена возможность сразу создавать лавочку с тегами
  internal/applications/initiator/app.go
  internal/domain/tags.go
  internal/policy/benches/policy.go
  internal/repository/postgres/benches/model.go
  internal/repository/postgres/benches/repository.go
  internal/repository/postgres/tags/model.go
  internal/repository/postgres/tags/repository.go
  internal/service/benches/service.go
  internal/service/tags/service.go
  internal/service/users/service.go
  internal/transport/httpv1/benches/benches.go
Labels: backend, feature, fix

#213 feat: FD-39 | Добавлена возможность переходить по якорным ссылкам
  app/components/Common/ui/Bench/BenchCard/BenchCard.tsx
  app/components/Common/ui/Bench/BenchCard/BenchesCard.styles.ts
  app/components/pages/BenchDetail/BenchDetailComments/BenchDetailComments.tsx
  app/hooks/useDidMount.ts
  app/utils/scrollToTop.ts
  pages/benches/[id]/index.tsx
Labels: frontend, feature

#215 Добавлен отдельный domain для токенов
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  internal/domain/users.go
  internal/transport/httpv1/users/users.go
Labels: backend, refactor

#218 Исправлена ошибка с получением адреса при создании лавочки
  internal/policy/benches/policy.go
Labels: backend, fix

#219 Исправлена формула подсчёта общего количества страниц в пагинации
  internal/policy/benches/policy.go
Labels: backend, fix

#223 Добавлен golangci-lint, отформатирован код
  .golangci.yml
  README.md
  cmd/initiator/main.go
  internal/applications/initiator/app.go
  internal/config/config.go
  internal/dto/benches.go
  internal/dto/comments.go
  internal/dto/reports.go
  internal/dto/tags.go
  internal/dto/users.go
  internal/repository/postgres/benches/model.go
  internal/repository/postgres/comments/model.go
  internal/repository/postgres/comments/repository.go
  internal/repository/postgres/interfaces.go
  internal/repository/postgres/reports/model.go
  internal/repository/postgres/reports/repository.go
  internal/repository/postgres/tags/model.go
  internal/repository/postgres/users/model.go
  internal/repository/postgres/users/repository.go
  internal/service/benches/service.go
  internal/service/bot/service.go
  internal/service/comments/service.go
  internal/service/notifications/mock.go
  internal/service/notifications/notifications.go
  internal/service/reports/service.go
  internal/service/users/service.go
  internal/storage/minio/storage.go
  internal/storage/redis/storage.go
  internal/transport/httpv1/benches/base.go
  internal/transport/httpv1/benches/benches.go
  internal/transport/httpv1/bot/base.go
  internal/transport/httpv1/bot/bot.go
  internal/transport/httpv1/comments/base.go
  internal/transport/httpv1/comments/comments.go
  internal/transport/httpv1/reports/base.go
  internal/transport/httpv1/reports/reports.go
  internal/transport/httpv1/tags/base.go
  internal/transport/httpv1/tags/tags.go
  internal/transport/httpv1/users/base.go
  internal/transport/httpv1/users/users.go
  pkg/client/postgres/client.go
  pkg/maps/yandex.go
  pkg/migrations/manager.go
Labels: backend, refactor

#224 Добавлена возможность обновлять теги у лавочки
  go.mod
  go.sum
  internal/policy/benches/policy.go
  internal/repository/postgres/tags/repository.go
  internal/service/tags/service.go
Labels: backend, feature
