Repository anime-team-pet-projects/lavochki-nsk, pull requests merged in 2023-01, with the labels that each got.

#94 Добавлено отношение tags для получения лавочки по ID
  internal/repository/postgres/benches_repository.go
Labels: backend

#95 refactor: FD-2 | Обновлён typescript, исправлены типы под новый TS, исправлено отображение слайдера
  app/components/Layouts/DefaultLayout/DefaultLayoutHeader/index.tsx
  app/components/pages/BenchDetail/BenchDetailComment/index.tsx
  app/components/pages/BenchDetail/BenchDetailComments/index.tsx
  app/components/pages/BenchDetail/BenchDetailSendComment/index.tsx
  app/components/pages/Home/HomeBench/index.tsx
  app/contexts/userContext.ts
  app/interfaces/bench.interface.ts
  app/interfaces/comment.interface.ts
  app/layouts/DefaultLayout/index.tsx
  app/services/Comment/CommentService.ts
  app/services/User/UserService.ts
  app/styles/general.scss
  app/types/bench.type.ts
  app/types/comment.type.ts
  app/types/user.type.ts
  package-lock.json
  package.json
  pages/_app.tsx
  pages/benches/[id]/index.tsx
  pages/index.tsx
Labels: frontend, fix

#96 Проведено review репозиториев и удалён applications/bot
  internal/applications/bot/app.go
  internal/repository/postgres/benches_repository.go
  internal/repository/postgres/comments_repository.go
  internal/repository/postgres/reports_repository.go
  internal/repository/postgres/tags_repository.go
  internal/repository/postgres/users_repository.go
  internal/service/benches/service.go
  internal/service/comments/service.go
  internal/service/reports/service.go
  internal/service/tags/service.go
  internal/service/users/service.go
  internal/transport/httpv1/comments/comments.go
Labels: backend

#98 refactor: FD-4 | Убраны глобальные интерфейсы, добавлен lint-stage
  .husky/pre-commit
  .prettierignore
  app/components/Common/Bench/BenchCard/BenchCard.tsx
  app/components/pages/BenchDetail/BenchDetailComment/index.tsx
  app/components/pages/BenchDetail/BenchDetailComments/index.tsx
  app/components/pages/BenchDetail/BenchDetailMap/index.tsx
  app/components/pages/BenchDetail/BenchDetailNear/BenchDetailNear.style.ts
  app/components/pages/BenchDetail/BenchDetailNear/BenchDetailNearSlider/index.tsx
  app/components/pages/BenchDetail/BenchDetailNear/index.tsx
  app/components/pages/BenchDetail/BenchDetailSlider/index.tsx
  app/components/pages/Benches/BenchesSidebar/BenchesSidebar.tsx
  app/components/pages/Benches/BenchesSort/BenchesSort.tsx
  app/components/pages/Home/HomeBench/index.tsx
  app/components/pages/Home/HomeBenches/index.tsx
  app/components/pages/Home/HomeMap/index.tsx
  app/interfaces/bench.interface.ts
  app/interfaces/comment.interface.ts
  app/interfaces/tag.interface.ts
  app/types/bench.type.ts
  app/types/comment.type.ts
  package.json
Labels: frontend, change

#105 feat : FD-6 | Добавлена кнопка, модальное окно, сервис для отправления жалобы на комментарий
  app/components/pages/BenchDetail/BenchDetailComment/BenchDetailComment.style.ts
  app/components/pages/BenchDetail/BenchDetailComment/BenchDetailCommentReport/index.tsx
  app/components/pages/BenchDetail/BenchDetailComment/BenchDetailCommentSend/index.tsx
  app/components/pages/BenchDetail/BenchDetailComment/index.tsx
  app/components/pages/BenchDetail/BenchDetailComments/index.tsx
  app/layouts/DefaultLayout/index.tsx
  app/services/Report/ReportService.ts
  app/types/report.type.ts
  pages/benches/[id]/index.tsx
Labels: frontend, feature

#106 feat: FD-7 | Добавлен _document.tsx
  pages/_document.tsx
  pages/api/hello.ts
Labels: frontend, feature

#107 feat: FD-8 | Добавлен отдельный компонент для карты. Изменены маркеры, кластеры
  app/components/pages/BenchDetail/BenchDetailMap/index.tsx
  app/components/pages/Home/HomeBench/HomeBenchSlider/index.tsx
  app/components/pages/Home/HomeMap/index.tsx
  app/components/ui/Benches/BenchesMap/BenchesMapPlacemarks/index.tsx
  app/components/ui/Benches/BenchesMap/index.tsx
  app/styles/vendor/y-maps/index.scss
  app/types/map.type.ts
  pages/benches/[id]/index.tsx
  public/BenchPlacemark.png
Labels: frontend, feature

#109 feat: FD-9 | Добавлен вывод адреса лавочек
  .env.example
  .eslintrc.json
  app/components/pages/BenchDetail/BenchDetailMap/index.tsx
  app/components/pages/Home/HomeBench/index.tsx
  app/components/pages/Home/HomeMap/index.tsx
  app/components/ui/Benches/BenchesMap/index.tsx
  app/types/bench.type.ts
  next.config.js
  pages/benches/[id]/index.tsx
  pages/index.tsx
Labels: frontend, feature

#112 Проведено review репозиториев, добавлен новый слой policy
  cmd/initiator/main.go
  go.mod
  go.sum
  internal/applications/initiator/app.go
  internal/domain/benches.go
  internal/domain/comments.go
  internal/domain/users.go
  internal/dto/benches.go
  internal/dto/users.go
  internal/policy/benches/policy.go
  internal/policy/bot/policy.go
  internal/policy/comments/policy.go
  internal/policy/notifications/policy.go
  internal/policy/reports/policy.go
  internal/policy/tags/policy.go
  internal/policy/users/policy.go
  internal/repository/postgres/benches.go
  internal/repository/postgres/benches/model.go
  internal/repository/postgres/benches/repository.go
  internal/repository/postgres/benches_repository.go
  internal/repository/postgres/comments.go
  internal/repository/postgres/comments/model.go
  internal/repository/postgres/comments/repository.go
  internal/repository/postgres/comments_repository.go
  internal/repository/postgres/interfaces.go
  internal/repository/postgres/postgres.go
  internal/repository/postgres/reports/model.go
  internal/repository/postgres/reports/repository.go
  internal/repository/postgres/reports_repository.go
  internal/repository/postgres/tags.go
  internal/repository/postgres/tags/model.go
  internal/repository/postgres/tags/repository.go
  internal/repository/postgres/tags_repository.go
  internal/repository/postgres/users.go
  internal/repository/postgres/users/model.go
  internal/repository/postgres/users/repository.go
  internal/repository/postgres/users_repository.go
  internal/service/benches/service.go
  internal/service/bot/service.go
  internal/service/comments/service.go
  internal/service/reports/service.go
  internal/service/tags/service.go
  internal/service/users/service.go
  internal/transport/httpv1/benches/benches.go
  internal/transport/httpv1/bot/bot.go
  internal/transport/httpv1/comments/comments.go
  internal/transport/httpv1/reports/reports.go
  internal/transport/httpv1/tags/tags.go
  internal/transport/httpv1/users/users.go
  pkg/client/postgres/client.go
  pkg/database/formatting.go
Labels: backend

#113 Изменено название функции, которая создаёт handler
  internal/applications/initiator/app.go
  internal/transport/httpv1/benches/benches.go
  internal/transport/httpv1/bot/bot.go
  internal/transport/httpv1/comments/comments.go
  internal/transport/httpv1/reports/reports.go
  internal/transport/httpv1/tags/tags.go
  internal/transport/httpv1/users/users.go
Labels: backend

#114 Исправлены координаты лавочек в репозитории
  internal/repository/postgres/benches/repository.go
Labels: backend, fix

#117 Добавлена сортировка для метода All в benches
  internal/repository/postgres/benches/repository.go
Labels: backend

#119 Исправлено ошибка с отсутствием результата при запросе в БД
  internal/repository/postgres/benches/repository.go
  internal/service/benches/service.go
  internal/service/users/service.go
  internal/transport/httpv1/benches/benches.go
  internal/transport/httpv1/comments/comments.go
Labels: backend

#122 feat: DD-1| Добавлены сервисы
  src/components/App/index.tsx
  src/components/Common/CommonHeader/index.tsx
  src/components/pages/BenchesModeration/BenchesModerationReasonDialog/BenchesModerationAcceptDialog.tsx
  src/components/pages/BenchesModeration/BenchesModerationReasonDialog/BenchesModerationDenyDialog.tsx
  src/layouts/DefaultLayout/index.tsx
  src/main.tsx
  src/pages/Benches/index.tsx
  src/pages/BenchesModeration/index.tsx
  src/services/Authorization/index.ts
  src/services/Axios/AxiosService.ts
  src/services/Axios/AxiosService.type.ts
  src/services/AxiosService/index.ts
  src/services/AxiosService/index.type.ts
  src/services/Bench/BenchService.ts
  src/services/Benches/index.ts
  src/services/Comment/CommentService.ts
  src/services/Report/ReportService.ts
  src/services/Tag/TagService.ts
  src/services/User/UserService.ts
  src/types/bench.type.ts
  src/types/comment.type.ts
  src/types/common.type.ts
  src/types/report.type.ts
  src/types/user.type.ts
  vite.config.ts
Labels: feature, dashboard

#123 feat: DD-2 | Обновлён сайдбар
  package-lock.json
  package.json
  src/assets/icons/home.svg
  src/assets/icons/user.svg
  src/components/App/index.tsx
  src/components/Common/CommonIcon/CommonIcon.interface.ts
  src/components/Common/CommonIcon/CommonIcon.tsx
  src/components/Common/CommonIcon/CommonIconStyles.ts
  src/components/Common/CommonSidebar/index.tsx
  src/components/Common/CommonSnackbar/index.tsx
  src/components/layouts/DefaultLayout/DefaultLayoutHeader/index.style.ts
  src/components/layouts/DefaultLayout/DefaultLayoutHeader/index.tsx
  src/components/layouts/DefaultLayout/DefaultLayoutSidebar/DefaultLayoutSidebar.contstant.ts
  src/components/layouts/DefaultLayout/DefaultLayoutSidebar/DefaultLayoutSidebar.style.ts
  src/components/layouts/DefaultLayout/DefaultLayoutSidebar/index.tsx
  src/layouts/DefaultLayout/index.tsx
  src/main.tsx
  src/styles/general.scss
  src/styles/resources/variables/_colors-base.scss
  src/styles/resources/variables/_colors.scss
  src/styles/resources/variables/index.scss
  src/styles/vendor/mui/_list-item.scss
  src/styles/vendor/mui/index.scss
  tsconfig.json
  vite.config.ts
Labels: feature, dashboard

#126 feat: DD-3 | Добавлены запросы для получения лавочек, обновлены стили
  package-lock.json
  package.json
  src/assets/fonts/Montserrat/Montserrat-Black.ttf
  src/assets/fonts/Montserrat/Montserrat-BlackItalic.ttf
  src/assets/fonts/Montserrat/Montserrat-Bold.ttf
  src/assets/fonts/Montserrat/Montserrat-BoldItalic.ttf
  src/assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
  src/assets/fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf
  src/assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
  src/assets/fonts/Montserrat/Montserrat-ExtraLightItalic.ttf
  src/assets/fonts/Montserrat/Montserrat-Italic.ttf
  src/assets/fonts/Montserrat/Montserrat-Light.ttf
  src/assets/fonts/Montserrat/Montserrat-LightItalic.ttf
  src/assets/fonts/Montserrat/Montserrat-Medium.ttf
  src/assets/fonts/Montserrat/Montserrat-MediumItalic.ttf
  src/assets/fonts/Montserrat/Montserrat-Regular.ttf
  src/assets/fonts/Montserrat/Montserrat-SemiBold.ttf
  src/assets/fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
  src/assets/fonts/Montserrat/Montserrat-Thin.ttf
  src/assets/fonts/Montserrat/Montserrat-ThinItalic.ttf
  src/components/layouts/DefaultLayout/DefaultLayoutHeader/index.tsx
  src/components/pages/Benches/BenchesDialog/BenchesDialogUpdate/index.tsx
  src/components/pages/Benches/BenchesTable/index.tsx
  src/components/pages/BenchesModeration/BenchesModerationTable/index.tsx
  src/hooks/useToggle.ts
  src/layouts/DefaultLayout/index.tsx
  src/main.tsx
  src/pages/Benches/index.tsx
  src/pages/BenchesModeration/index.tsx
  src/services/Bench/BenchService.ts
  src/styles/fonts.scss
  src/styles/general.scss
  src/styles/main.scss
  src/styles/resources/variables/_colors-base.scss
  src/types/bench.type.ts
Labels: feature, dashboard

#127 Исправлена ошибка при GET запросе на все лавочки на модерации
  internal/transport/httpv1/benches/benches.go
Labels: backend

#130 feat: DD-4 | Добавлено получение детальной лавочки, комментов на модерации
  src/components/App/index.tsx
  src/components/pages/Benches/BenchesTable/index.tsx
  src/components/pages/CommentsModeration/CommentsModerationTable/index.tsx
  src/main.tsx
  src/pages/Benches/index.tsx
  src/pages/BenchesModeration/index.tsx
  src/pages/CommentsModeration/index.tsx
  src/services/Report/ReportService.ts
  src/styles/vendor/mui/_table.scss
  src/styles/vendor/mui/index.scss
  src/types/comment.type.ts
Labels: feature, dashboard

#131 feat: DD-5 | Добавлен вывод тегов
  src/components/App/index.tsx
  src/components/pages/Tags/TagsTable/index.tsx
  src/pages/Tags/index.tsx
Labels: feature, dashboard

#133 Исправлена ошибка с 403 и адекватным ответом
  pkg/auth/manager.go
Labels: backend, fix

#135 Добавлена подробная ошибка при несовпадение роли
  pkg/auth/manager.go
Labels: backend, feature

#137 Исправлены ошибки авторизации
  pkg/auth/manager.go
Labels: backend, fix

#138 Исправлены поля для комментариев на которые пожаловались
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  internal/domain/reports.go
  internal/transport/httpv1/reports/reports.go
Labels: backend, fix

#139 Добавлен endpoint для получения всех пользователей
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  internal/policy/users/policy.go
  internal/repository/postgres/users/repository.go
  internal/service/users/service.go
  internal/transport/httpv1/users/users.go
Labels: backend, feature

#141 Обновлён swagger
  docker-compose.yaml
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
Labels: backend, feature

#142 Исправлены методы в users handlers
  internal/transport/httpv1/users/users.go
Labels: backend

#143 Удалён ненужный параметр из swagger'a
  internal/transport/httpv1/users/users.go
Labels: backend, fix

#145 feat : DD-7 | Добавлена таблица пользователей
  src/components/App/index.tsx
  src/components/pages/Users/UsersTable/index.tsx
  src/pages/Tags/index.tsx
  src/pages/Users/index.tsx
  src/services/User/UserService.ts
Labels: frontend, feature

#147 Добавлен CRUD для benches
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  internal/apperror/error.go
  internal/apperror/middleware.go
  internal/dto/benches.go
  internal/policy/benches/policy.go
  internal/service/benches/service.go
  internal/transport/httpv1/benches/benches.go
Labels: backend, feature

#149 Добавлены теги mapstructure для всех моделей репозиториев
  internal/repository/postgres/benches/model.go
  internal/repository/postgres/comments/model.go
  internal/repository/postgres/reports/model.go
  internal/repository/postgres/tags/model.go
  internal/repository/postgres/users/model.go
Labels: backend, feature

#150 Добавлена логика для пагинации
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  internal/policy/benches/policy.go
  internal/repository/model/interfaces.go
  internal/repository/model/options.go
  internal/repository/postgres/benches/repository.go
  internal/service/benches/service.go
  internal/transport/httpv1/benches/benches.go
  pkg/api/paginate/middleware.go
Labels: backend, feature

#152 Добавлены новые параметры для пагинации
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  internal/domain/benches.go
  internal/policy/benches/policy.go
  internal/repository/postgres/benches/repository.go
  internal/service/benches/service.go
Labels: backend, feature

#155 refactor: DD-9 | Исправлено получение данных всвязи с изменением backend'а
  src/assets/icons/close.svg
  src/assets/icons/refresh.svg
  src/components/pages/Benches/BenchesTable/index.tsx
  src/components/pages/BenchesModeration/BenchesModerationTable/index.tsx
  src/components/pages/ReportComments/ReportCommentsTable/index.tsx
  src/main.tsx
  src/pages/Benches/index.tsx
  src/pages/BenchesModeration/index.tsx
  src/services/Bench/BenchService.ts
  src/services/Comment/CommentService.ts
  src/services/Report/ReportService.ts
  src/types/bench.type.ts
  src/types/comment.type.ts
Labels: dashboard, refactor

#156 refactor: DD-10 | Рефакторинг кода
  src/components/App/index.tsx
  src/components/layouts/DefaultLayout/DefaultLayoutRoutes/DefaultLayoutRoutes.constant.tsx
  src/components/layouts/DefaultLayout/DefaultLayoutRoutes/index.tsx
  src/components/pages/Benches/BenchesDetail/index.tsx
  src/components/pages/Benches/BenchesDialog/BenchesDialogUpdate/index.tsx
  src/components/pages/Benches/BenchesTable/index.tsx
  src/components/pages/BenchesModeration/BenchesModerationReasonDialog/BenchesModerationAcceptDialog.tsx
  src/components/pages/BenchesModeration/BenchesModerationReasonDialog/BenchesModerationDenyDialog.tsx
  src/components/pages/Tags/TagsTable/index.tsx
  src/layouts/DefaultLayout/index.tsx
  src/pages/Benches/index.tsx
  src/pages/BenchesModeration/index.tsx
Labels: dashboard, refactor

#158 refactor: FD-10 | Рефактор интгеграции
  app/components/Layouts/DefaultLayout/DefaultLayoutFooter/DefaultLayoutFooter.style.ts
  app/components/ui/Bench/BenchCard/BenchCard.tsx
  app/components/ui/Benches/BenchesMap/BenchesMapPlacemarks/index.tsx
  app/layouts/DefaultLayout/DefaultLayout.style.ts
  app/layouts/DefaultLayout/index.tsx
  app/services/Bench/BenchService.ts
  app/styles/general.scss
  app/styles/resources/mixins/_other.scss
  app/types/bench.type.ts
  pages/_app.tsx
  pages/_document.tsx
  pages/benches/[id]/index.tsx
  pages/benches/index.tsx
  pages/index.tsx
Labels: frontend, change

#159 feat: FD-11 | Добавлена возможность перехода к лавочке при клике на иконку
  .eslintrc.json
  app/components/pages/BenchDetail/BenchDetailComment/BenchDetailCommentReport/index.tsx
  app/components/pages/Home/HomeBench/index.tsx
  app/components/pages/Home/HomeBenches/index.tsx
  app/components/pages/Home/HomeMap/index.tsx
  app/components/ui/Benches/BenchesMap/BenchesMapPlacemarks/index.tsx
  app/components/ui/Benches/BenchesMap/index.tsx
  app/types/map.type.ts
  app/utils/scrollToTop.ts
  pages/index.tsx
Labels: frontend, feature

#160 feat: FD-12 | Убраны snakebar и Common Icon из SSR
  app/components/Common/CommonIcon/CommonIcon.tsx
  app/components/Common/CommonSnackbar/index.tsx
  app/components/Layouts/DefaultLayout/DefaultLayoutMenu/index.tsx
Labels: frontend, change

#161 fix: FD-13 | Изменена логика клика на кластер
  app/components/ui/Benches/BenchesMap/BenchesMapPlacemarks/index.tsx
  app/components/ui/Benches/BenchesMap/index.tsx
  pages/index.tsx
Labels: frontend, fix

#162 fix: FD-14 | Исправлено отображение детальной лавочки
  app/components/pages/BenchDetail/BenchDetailMap/index.tsx
  app/components/pages/BenchDetail/BenchDetailNear/BenchDetailNearSlider/index.tsx
  app/components/ui/Benches/BenchesMap/BenchesMapPlacemarks/index.tsx
  pages/benches/[id]/index.tsx
Labels: frontend, fix

#166 feat: FD-16 | Добавлен бесконечный скролл на главной странице, но убран поиск улиц
  app/components/Common/CommonLoader/CommonLoader.style.ts
  app/components/Common/CommonLoader/index.tsx
  app/layouts/DefaultLayout/DefaultLayout.style.ts
  app/layouts/DefaultLayout/index.tsx
  app/services/Bench/BenchService.ts
  app/types/bench.type.ts
  package-lock.json
  package.json
  pages/benches/[id]/index.tsx
  pages/index.tsx
Labels: frontend, feature

#167 feat: FD-17 | Добавлена пагинация на страницу всех лавочек
  .eslintrc.json
  app/services/Bench/BenchService.ts
  pages/benches/index.tsx
Labels: frontend, feature

#168 feat: FD-18 | Добавлен скелетон для лавочек на странице всех лавочек
  app/components/pages/Benches/BenchesSidebar/BenchesSidebar.styles.ts
  app/components/pages/Benches/BenchesSidebar/BenchesSidebar.tsx
  app/components/ui/Bench/BenchCard/BenchCardSkeleton/index.tsx
  pages/benches/index.tsx
Labels: frontend, feature
